### ISSUE TITLE
psiturk.js file is missing?

### ISSUE THREAD

**Issue by hstojic** [jspsych/sample-jspsych-psiturk-experiment#1]
The experiment seems to work fine when started with psiturk, but i noticed that exp.html calls psiturk.js in static/js/ however that script is not there.

**Comment by jodeleeuw** [comment]
PsiTurk adds this file automatically when you run it in PsiTurk. It's not meant to be included in the static/js/ directory.

**Comment by hstojic** [comment]
Ok, thanks for the quick response!
